name: Build Windows DLL and EXE

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install MinGW cross-compiler
        run: sudo apt-get update && sudo apt-get install -y mingw-w64

      - name: Build nsfw.dll from nsfw.cpp
        run: |
          x86_64-w64-mingw32-g++ -shared -o nsfw.dll nsfw.cpp

      - name: Build nsfw.exe from nsfw.cpp
        run: |
          x86_64-w64-mingw32-g++ -o nsfw.exe nsfw.cpp

      - name: Upload DLL artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows-DLL
          path: nsfw.dll

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows-EXE
          path: nsfw.exe
